# Generated by Django 4.1 on 2022-09-01 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('population', models.IntegerField(default=0)),
                ('nb_lits_touristiques', models.IntegerField(default=0)),
                ('chomage', models.IntegerField(default=0)),
                ('activity', models.IntegerField(default=0)),
                ('nb_medecin', models.IntegerField(default=0)),
                ('nuitees_touristiques', models.IntegerField(default=0)),
                ('nb_eleves_primaire', models.IntegerField(default=0)),
                ('nb_eleves_college', models.IntegerField(default=0)),
                ('nb_eleves_lycee', models.IntegerField(default=0)),
            ],
        ),
    ]
