# Generated by Django 4.1 on 2022-09-02 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('region', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='year',
            field=models.IntegerField(default=0),
        ),
    ]
