# Generated by Django 3.2.15 on 2022-09-04 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('region', '0002_region_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indicateur', models.CharField(max_length=20)),
            ],
        ),
    ]
