# Generated by Django 3.2.15 on 2022-09-05 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('region', '0003_region1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Region1',
        ),
    ]
